### ISSUE TITLE
Comentarios avance1

### ISSUE THREAD

**Issue by AliciaMstt** [Ferxengutta/Proyecto-Final-Bioinf2017-II#1]
OK

👍

**Comment by AzaleaGuerra** [comment]
Suena bien. ¿Vas a ensamblar de novo o usarás un genoma de referencia?

**Comment by Ferxengutta** [comment]
ok revisado comentario Alicia, perdon por tardar en contestar

**Comment by Ferxengutta** [comment]
Pensaba hacerlo de Novo Azalea, pero si me sugieres que es mejor buscar el genoma de referencia lo uso.

Saludos
