### ISSUE TITLE
avances 2

### ISSUE THREAD

**Issue by AzaleaGuerra** [Ferxengutta/Proyecto-Final-Bioinf2017-II#2]
¿Ya has instalado Stacks? Recuerda que puede ser un poco complicado. ¿Cuál es tu pregunta principal a contestar? ¿Son datos propios? Si tu pregunta es filogenética quizá te conviene más usar Pyrad, Stacks ha recibido críticas porque tiene problemas en el demultiplexeo, además Pyrad permite incluir indels. 
Te dejo el link a un artículo donde comparan diferentes pipelines.
http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0161333

Finalmente, ¿hay algún genoma que puedas usar de referencia? Tiene sus ventajas usar un genoma de referencia porque podrías saber en dónde están las variantes y si son codificantes, así que considéralo.

**Comment by Ferxengutta** [comment]
Gracias Azalea, por la información me aclaro unas dudas que tenía.

Saludos
